services:
  - type: web
    name: resume-ranker
    env: python
    rootDir: .
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k uvicorn.workers.UvicornWorker src.api.main:app --bind 0.0.0.0:$PORT"



