services:
  - type: web
    name: resume-ranker
    env: python
    plan: free
    runtime: python3.10
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn src.api.main:app -k uvicorn.workers.UvicornWorker

