services:
  - type: web
    name: resume-ranker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k uvicorn.workers.UvicornWorker src.api.main:app --bind 0.0.0.0:$PORT"
    pythonVersion: "3.10.12"
