services:
  - type: web
    name: ats-checker
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
